import * as dotenv from 'dotenv'
dotenv.config()

const PORT = process.env.PORT
const DBURL = process.env.DBURL
const JWT_SECRET = process.env.JWT_SECRET
const ACCESSTOKEN_SECRET = process.env.ACCESSTOKEN_SECRET
const ACCESSTOKEN_EXPIRE = process.env.ACCESSTOKEN_EXPIRE
const REFRESHTOKEN_SECRET = process.env.REFRESHTOKEN_SECRET
const REFRESHTOKEN_EXPIRE = process.env.REFRESHTOKEN_EXPIRE
export { PORT, DBURL, JWT_SECRET, ACCESSTOKEN_EXPIRE, ACCESSTOKEN_SECRET, REFRESHTOKEN_EXPIRE, REFRESHTOKEN_SECRET }